#!/usr/bin/env python3
"""Rebuild numerical supplement tables and oracle checks from saved fits.
Publication figures are generated by manuscript-figures, not this script.
"""
from paired_benchmark import *
import pandas as pd

def ms(value):
    a=np.asarray(value,float)
    return f'{a.mean():.3g} ({a.std(ddof=1):.2g})'

def tex_sci(value):
    if value==0:return '0'
    mantissa,exponent=f'{value:.2e}'.split('e')
    return mantissa+r'\times 10^{'+str(int(exponent))+'}'

def main():
    df=pd.read_csv(BASE/'paired_results.csv')
    multi=pd.read_csv(BASE/'multistart_results.csv')
    methods=['r_exact','pot_exact','sinkhorn_0.1','sinkhorn_0.3','sinkhorn_1']
    supports=[50,100,200]
    exact=df[df.method=='pot_exact'].set_index(['rep','support'])
    lines=[r'\begin{table}[htbp]',r'\centering',r'\small',
       r'\caption{Paired Gaussian solver diagnostics across ten independent problems per support size. Entries for objective differences and iterations are means (sample SD). Each objective difference subtracts the exact Python/POT result on the same inputs and initialization; differences below $10^{-10}$ are rounded to zero. The final two columns give the number of iteration-limit exits and the largest final normalized residual; capped runs remain in all summaries.}',
       r'\label{tab:paired-gaussian-diagnostics}',r'\begin{tabular}{llrrrr}',r'\toprule',
       r'$m$ & Implementation & $F-F_{\mathrm{POT}}$ & Updates & Capped & Max. residual \\',r'\midrule']
    labels_tex=['R/T4 exact MM','Python/POT exact',r'Sinkhorn $0.1s^2$',r'Sinkhorn $0.3s^2$',r'Sinkhorn $s^2$']
    for m in supports:
        for method,label in zip(methods,labels_tex):
            g=df[(df.support==m)&(df.method==method)].sort_values('rep')
            diffs=[r.objective-exact.loc[(r.rep,r.support),'objective'] for r in g.itertuples()]
            diffs=[0. if abs(x)<1e-10 else x for x in diffs]
            lines.append(f'{m} & {label} & {ms(diffs)} & {ms(g.niter)} & {sum(g.status!="converged")} & '+f'${tex_sci(g.residual.max())}$'+r' \\')
        if m!=supports[-1]:lines.append(r'\addlinespace')
    lines += [r'\bottomrule',r'\end{tabular}',r'\end{table}']
    (BASE/'paired_diagnostics_table.tex').write_text('\n'.join(lines)+'\n')

    mlines=[r'\begin{table}[htbp]',r'\centering',r'\small',r'\caption{Initialization sensitivity for three fixed Gaussian problems with $m=50$. Each problem uses five independent pooled $k$-means starts. Differences are relative to the best objective attained among these five starts, not a certified global optimum.}',r'\label{tab:gaussian-multistart}',r'\begin{tabular}{rrrrrr}',r'\toprule',r'Problem & Best $F$ & Median $\Delta F$ & Max. $\Delta F$ & Update range & Capped \\',r'\midrule']
    for rep,g in multi.groupby('rep'):
        delta=g.objective-g.objective.min()
        mlines.append(f'{rep} & {g.objective.min():.6f} & {delta.median():.4g} & {delta.max():.4g} & {g.niter.min()}--{g.niter.max()} & {sum(g.status!="converged")}'+r' \\')
    mlines += [r'\bottomrule',r'\end{tabular}',r'\end{table}']
    (BASE/'multistart_table.tex').write_text('\n'.join(mlines)+'\n')

    oracle=[]
    for rep in range(1,4):
        cid,data=create_case(rep,100)
        X=np.loadtxt(BASE/'runs'/f'{cid}_pot_exact_support.csv',delimiter=',')
        for n in (500,1000,2000):
            truth=data['oracle'][:n]
            oracle.append(dict(rep=rep,n_oracle=n,semi_w2=np.sqrt(ot.emd2(data['bary_masses'],ot.unif(n),distances(X,truth)))))
    write_rows(BASE/'oracle_sensitivity.csv',oracle)
    stats={
      'final_rows':len(df),'paired_repetitions_per_support':10,'exact_native_max_difference':df.pot_native_max_difference.max(),
      'largest_marginal_error_across_all_iterations':df.max_marginal_error.max(),
      'exact_objective_pair_max_abs_difference':float(np.max(np.abs(df[df.method=='r_exact'].sort_values(['rep','support']).objective.values-df[df.method=='pot_exact'].sort_values(['rep','support']).objective.values))),
      'caps_by_method':{method:int(sum(df[df.method==method].status!='converged')) for method in methods},
      'median_runtime_by_method':{method:float(df[df.method==method].runtime_sec.median()) for method in methods},
      'mean_w2_by_method':{method:float(df[df.method==method].semi_w2.mean()) for method in methods},
      'mean_cov_error_by_method':{method:float(df[df.method==method].cov_error.mean()) for method in methods},
      'max_residual_by_method':{method:float(df[df.method==method].residual.max()) for method in methods},
      'any_inner_nonconvergence':bool(any(df[df.method.str.startswith('sinkhorn')].all_inner_converged.astype(str).str.lower()!='true')),
      'multistart_capped':int(sum(multi.status!='converged')),
      'multistart_max_objective_range':float(multi.groupby('rep').objective.apply(lambda v:v.max()-v.min()).max())}
    (BASE/'summary.json').write_text(json.dumps(stats,indent=2))
    print(json.dumps(stats,indent=2))

if __name__=='__main__':main()
